const $=s=>document.querySelector(s), money=n=>'$'+Math.round(n).toLocaleString('en-US'), cash=n=>(n<0?'-$':'$')+Math.abs(n).toFixed(2), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const stockSeed=[
['AMW','American Motor Works','Automotive',31.40,.024,.040],['DMW','Dearborn Motor Works','Automotive',24.80,.018,.043],['CMC','Continental Motor Co.','Automotive',18.65,.016,.048],
['NAC','National Aircraft Corp.','Aviation',16.20,.008,.060],['PAW','Pacific Aeronautical Works','Aviation',12.75,.000,.068],['CAA','Columbia Aircraft & Aviation','Aviation',9.40,.000,.072],
['HBC','Hudson Banking Corp.','Banking',42.60,.032,.028],['FNT','First National Trust','Banking',36.15,.030,.026],['USB','Union States Bank','Banking',28.90,.027,.032],
['ATL','Atlantic Chemical','Chemicals',24.10,.025,.040],['UCD','Union Chemical & Dye','Chemicals',38.70,.021,.045],['ACP','American Chemical & Powder','Chemicals',44.30,.020,.048],
['NRT','National Radio & Telegraph','Communications',18.75,.015,.052],['CTC','Continental Telegraph Co.','Communications',27.20,.026,.038],['ATG','American Telephone & Telegraphic','Communications',61.80,.038,.026],
['AEC','American Electrical Corp.','Electrical',34.10,.026,.040],['WEC','Western Electric Apparatus','Electrical',28.35,.024,.043],['RMI','Republic Motor & Instrument','Electrical',21.90,.018,.050],
['MEC','Metropolitan Edison Co.','Utilities',39.60,.042,.024],['CPL','Capital Power & Light','Utilities',32.25,.045,.025],['GPL','Great Plains Light & Power','Utilities',25.70,.041,.028],
['ACS','American Consolidated Steel','Steel',29.85,.020,.052],['LSI','Liberty Steel & Iron','Steel',23.40,.018,.055],['RST','Republic Steel Trust','Steel',17.95,.012,.060],
['NPT','National Petroleum','Petroleum',35.75,.031,.038],['LSP','Lone Star Petroleum','Petroleum',22.60,.028,.045],['GOC','Gulf & Ocean Oil','Petroleum',19.30,.026,.048],
['PAR','Pennsylvania & Atlantic RR','Railroads',27.45,.036,.042],['NCR','New York Continental RR','Railroads',33.80,.040,.038],['CPR','Continental Pacific Railway','Railroads',21.15,.033,.046],['GNR','Great Northern & Western RR','Railroads',25.90,.035,.043],
['NMC','National Mercantile & Catalog','Retail',26.30,.022,.044],['FWC','Franklin Ward & Co.','Retail',19.85,.020,.048],['WFT','Worthington Five & Ten','Retail',14.60,.027,.036],
['AHW','American Harvester Works','Machinery',37.10,.025,.041],['CMW','Central Machine Works','Machinery',20.40,.019,.050],['UTM','Union Tool & Machine','Machinery',15.75,.016,.055],
['INM','International Nickel & Metals','Mining',30.55,.030,.046],['CCM','Continental Copper & Mining','Mining',18.20,.022,.058],['AMC','American Metals Corp.','Mining',24.65,.026,.052],
['ATS','Atlantic Transport & Steamship','Shipping',17.80,.025,.055],['USL','United States Lines & Freight','Shipping',22.30,.028,.050],['PSN','Pacific Steam Navigation','Shipping',13.95,.020,.060],
['NFC','National Foods Corp.','Food',28.40,.033,.030],['APC','American Provision Co.','Food',21.60,.031,.034],['GMC','Great Mills Corp.','Food',16.90,.029,.036],
['ACC','American Consumer Corp.','Consumer',25.15,.028,.038],['HHA','Household & Home Appliances','Consumer',19.45,.020,.048],['USG','United Soap & Goods','Consumer',23.75,.032,.033],['RTA','Republic Tobacco & Allied','Consumer',34.50,.045,.035]
];
const DAY_SECONDS=3600, MARKET_TICK_MS=5000, SAVE_KEY='federalElectricSave';
function makeStocks(){return Object.fromEntries(stockSeed.map(([ticker,name,sector,price,yieldRate,vol])=>[ticker,{name,sector,price,prev:price,open:price,yieldRate,vol}]))}
function makePortfolio(){return Object.fromEntries(stockSeed.map(x=>[x[0],{shares:0,cost:0}]))}
function nextBusinessDay(iso){let d=new Date(iso+'T12:00:00');do d.setDate(d.getDate()+1);while(d.getDay()===0||d.getDay()===6);return d.toISOString().slice(0,10)}
function monthKey(iso){return iso.slice(0,7)}
function rollRaidDays(iso){const d=new Date(iso+'T12:00:00'),y=d.getFullYear(),m=d.getMonth(),days=new Date(y,m+1,0).getDate(),count=1+Math.floor(Math.random()*2),set=new Set();while(set.size<count){const n=1+Math.floor(Math.random()*days),x=new Date(y,m,n);if(x.getDay()!==0)set.add(n)}return [...set].sort((a,b)=>a-b)}
function rollStarRaidMonth(iso){const d=new Date(iso+'T12:00:00');d.setMonth(d.getMonth()+4+Math.floor(Math.random()*5));return monthKey(d.toISOString().slice(0,10))}
function pokerRisk(circle){return circle==='working'?.012:circle==='middle'?.007:.003}
const initial=()=>({version:3,gameDate:'1938-01-03',dayRemaining:DAY_SECONDS,companyCash:50000,personalCash:12000,debt:0,reputation:55,workers:80,machinery:92,inventory:0,materials:{copper:6000,glass:6000,tungsten:3500},lastRevenue:0,lastExpenses:0,ledger:[],stocks:makeStocks(),portfolio:makePortfolio(),transactions:[],marketWire:'Industrial shares open mixed as investors weigh credit conditions and the pace of recovery.',headline:'INDUSTRY WATCHES RECOVERY WITH CAUTION',story:'Manufacturers enter 1938 balancing weak demand against hopes for renewed industrial activity.',societyStory:'Washington begins another business day of meetings, dinners, private clubs and quiet conversations.',newsArchive:[],notes:[],contacts:{madamStar:{name:'Madam Star',trust:0,met:false},bookie:{name:'Eddie Doyle, bookmaker',trust:0,met:false},hayes:{name:'Commissioner Arthur Hayes',trust:0,resentment:0,met:false}},raidMonth:'1938-01',raidDays:rollRaidDays('1938-01-03'),starNextRaidMonth:rollStarRaidMonth('1938-01-03'),starRaidOccurred:false,bookieKnown:false,elitePokerUnlocked:false,lastRaidOutcome:null});
let S=initial(), marketTimer=null, clockTimer=null, autosaveTimer=null;
function migrate(x){const fresh=initial();if(!x)return fresh;Object.assign(fresh,x,{version:3});if(!x.gameDate){fresh.gameDate='1938-01-03';fresh.dayRemaining=DAY_SECONDS}fresh.stocks=makeStocks();for(const [k,v] of Object.entries(x.stocks||{})){if(fresh.stocks[k])Object.assign(fresh.stocks[k],v,{open:+v.open||+v.price||fresh.stocks[k].price})}fresh.portfolio=makePortfolio();for(const [k,v] of Object.entries(x.portfolio||{})){if(!fresh.portfolio[k])continue;fresh.portfolio[k]=typeof v==='number'?{shares:v,cost:v*(fresh.stocks[k]?.price||0)}:{shares:+v.shares||0,cost:+v.cost||0}}fresh.transactions=x.transactions||[];fresh.newsArchive=x.newsArchive||[];fresh.notes=x.notes||[];fresh.contacts=Object.assign(initial().contacts,x.contacts||{});fresh.raidMonth=x.raidMonth||monthKey(fresh.gameDate);fresh.raidDays=x.raidDays||rollRaidDays(fresh.gameDate);fresh.starNextRaidMonth=x.starNextRaidMonth||rollStarRaidMonth(fresh.gameDate);fresh.starRaidOccurred=!!x.starRaidOccurred;fresh.elitePokerUnlocked=!!x.elitePokerUnlocked;return fresh}
function save(silent=true){localStorage.setItem(SAVE_KEY,JSON.stringify(S));if(!silent)note('Company books saved.')}
function loadInitial(){const raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem('continentalElectricSave');if(raw){try{S=migrate(JSON.parse(raw));save(true)}catch(e){S=initial()}}}
function displayDate(){return new Date(S.gameDate+'T12:00:00').toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
function clockText(){const t=Math.max(0,Math.ceil(S.dayRemaining)),m=Math.floor(t/60),s=t%60;return String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function capacity(){return Math.floor(S.workers*20*(S.machinery/100))}
function portfolioValue(){return Object.entries(S.portfolio).reduce((a,[k,p])=>a+p.shares*S.stocks[k].price,0)}
function portfolioCost(){return Object.values(S.portfolio).reduce((a,p)=>a+p.cost,0)}
function marketIndex(){const current=Object.values(S.stocks).reduce((a,x)=>a+x.price,0),base=stockSeed.reduce((a,x)=>a+x[3],0);return current/base*100}
function signed(n){return (n>=0?'+':'')+n.toFixed(2)+'%'}
function note(t){$('#notice').textContent=t;$('#productionNote').textContent=t}
function render(){
 $('#businessDate').textContent=displayDate();$('#dayClock').textContent=clockText();$('#marketStatus').textContent=S.dayRemaining>0?'EXCHANGE OPEN':'CLOSING BOOKS';
 $('#companyCash').textContent=money(S.companyCash);$('#personalCash').textContent=money(S.personalCash);$('#marketCash').textContent=money(S.personalCash);$('#companyValue').textContent=money(S.companyCash+S.inventory*.14+Object.values(S.materials).reduce((a,b)=>a+b*.015,0));$('#reputation').textContent=Math.round(S.reputation)+'/100';$('#workers').textContent=S.workers;$('#machinery').textContent=S.machinery.toFixed(1)+'%';$('#capacity').textContent=capacity().toLocaleString();$('#inventory').textContent=S.inventory.toLocaleString();$('#dateFoot').textContent=displayDate();$('#paperDate').textContent=displayDate().toUpperCase();$('#headline').textContent=S.headline;$('#story').textContent=S.story;$('#societyStory').textContent=S.societyStory;
 const idx=marketIndex();$('#marketIndex').textContent=idx.toFixed(2);$('#marketStory').textContent='Federal Exchange index stands at '+idx.toFixed(2)+'. '+S.marketWire;$('#marketWire').textContent=S.marketWire;const pv=portfolioValue(),ug=pv-portfolioCost();$('#portfolio').textContent=money(pv);$('#unrealized').textContent=cash(ug);$('#unrealized').className=ug>=0?'gain':'loss';
 $('#ledger').innerHTML=S.ledger.slice(-10).reverse().map(x=>'<tr><td>'+x.date+'</td><td>'+money(x.rev)+'</td><td>'+money(x.exp)+'</td><td>'+money(x.rev-x.exp)+'</td></tr>').join('')||'<tr><td colspan="4" class="empty">No closed business days yet.</td></tr>';
 const lots={copper:[1000,180],glass:[1000,95],tungsten:[500,160]};$('#materials').innerHTML=Object.entries(lots).map(([k,[qty,cost]])=>'<tr><td>'+k[0].toUpperCase()+k.slice(1)+'</td><td>'+Math.floor(S.materials[k]).toLocaleString()+'</td><td>'+money(cost)+'</td><td><button onclick="buyMaterial(\''+k+'\','+qty+','+cost+')">Buy '+qty+'</button></td></tr>').join('');
 renderStocks();renderHoldings();renderTransactions();renderNotes();renderArchive();renderWashington()
}
function renderStocks(){const q=$('#stockSearch').value.trim().toLowerCase(),sector=$('#sectorFilter').value;const rows=Object.entries(S.stocks).filter(([k,x])=>(sector==='All'||x.sector===sector)&&(!q||k.toLowerCase().includes(q)||x.name.toLowerCase().includes(q)));$('#stocks').innerHTML=rows.map(([k,x])=>{const ch=(x.price/x.open-1)*100,p=S.portfolio[k];return '<tr><td><b>'+k+'</b></td><td>'+x.name+'</td><td>'+x.sector+'</td><td>$'+x.price.toFixed(2)+'</td><td class="'+(ch>=0?'gain':'loss')+'">'+signed(ch)+'</td><td>'+(x.yieldRate*100).toFixed(1)+'%</td><td>'+p.shares+'</td><td><div class="trade-buttons"><button onclick="trade(\''+k+'\',1)">Buy</button><button onclick="trade(\''+k+'\',-1)">Sell</button></div></td></tr>'}).join('')}
function renderHoldings(){const rows=Object.entries(S.portfolio).filter(([,p])=>p.shares>0);$('#holdings').innerHTML=rows.map(([k,p])=>{const x=S.stocks[k],avg=p.cost/p.shares,mv=p.shares*x.price,g=mv-p.cost;return '<tr><td>'+k+'</td><td>'+p.shares+'</td><td>$'+avg.toFixed(2)+'</td><td>$'+x.price.toFixed(2)+'</td><td>'+cash(mv)+'</td><td class="'+(g>=0?'gain':'loss')+'">'+cash(g)+'</td></tr>'}).join('')||'<tr><td colspan="6" class="empty">No securities held.</td></tr>'}
function renderTransactions(){$('#transactions').innerHTML=S.transactions.slice(-15).reverse().map(t=>'<tr><td>'+t.date+'</td><td>'+t.action+'</td><td>'+t.ticker+'</td><td>'+t.shares+'</td><td>$'+(+t.price).toFixed(2)+'</td><td>'+cash(t.amount)+'</td></tr>').join('')||'<tr><td colspan="6" class="empty">No transactions yet.</td></tr>'}
function renderNotes(){$('#notes').innerHTML=S.notes.slice().reverse().map(n=>'<div class="note-entry"><b>'+n.date+'</b> · '+escapeHtml(n.text)+'<br><small>Source: '+escapeHtml(n.source||'personal observation')+'</small></div>').join('')||'<p class="empty">No notes recorded.</p>'}
function renderArchive(){$('#newsArchive').innerHTML=S.newsArchive.slice().reverse().map(n=>'<div class="archive-entry"><b>'+n.date+'</b><br>'+escapeHtml(n.headline)+'</div>').join('')||'<p class="empty">No editions archived.</p>'}
function renderWashington(){const c=S.contacts;$('#starRelation').textContent=c.madamStar.met?(c.madamStar.trust>2?'Warm acquaintance':'Acquainted'):'Not yet acquainted';$('#contacts').innerHTML=Object.values(c).filter(x=>x.met).map(x=>'<div class="contact"><b>'+escapeHtml(x.name)+'</b><br><small>Known contact. Their private motives and reliability are not shown.</small></div>').join('')||'<p class="empty">No established contacts.</p>';$('#meetBookie').disabled=!c.madamStar.met||S.bookieKnown;$('#pokerElite').disabled=!S.elitePokerUnlocked}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.buyMaterial=(k,q,c)=>{if(S.companyCash<c)return note('Insufficient company cash.');S.companyCash-=c;S.materials[k]+=q;S.lastExpenses+=c;note('Purchase order entered.');save();render()}
window.trade=(k,direction)=>{const qty=+$('select#lotSize').value,x=S.stocks[k],p=S.portfolio[k],commission=Math.max(1,qty*.05),gross=x.price*qty;if(direction>0){const total=gross+commission;if(S.personalCash<total)return note('Insufficient personal cash for purchase and commission.');S.personalCash-=total;p.shares+=qty;p.cost+=total;S.transactions.push({date:displayDate(),action:'BUY',ticker:k,shares:qty,price:x.price,amount:-total})}else{if(p.shares<qty)return note('Not enough '+k+' shares.');const avg=p.cost/p.shares,proceeds=gross-commission;p.shares-=qty;p.cost=Math.max(0,p.cost-avg*qty);S.personalCash+=proceeds;S.transactions.push({date:displayDate(),action:'SELL',ticker:k,shares:qty,price:x.price,amount:proceeds})}save();render()}
function moveMarket(){const sectors=[...new Set(Object.values(S.stocks).map(x=>x.sector))],sectorMove={};sectors.forEach(s=>sectorMove[s]=(Math.random()-.5)*.0012);const broad=(Math.random()-.5)*.0008;let leaders=[];for(const [k,x] of Object.entries(S.stocks)){x.prev=x.price;const company=(Math.random()-.5)*x.vol*.025,move=broad+sectorMove[x.sector]+company;x.price=Math.max(1,Math.round(x.price*(1+move)*100)/100);leaders.push([k,(x.price/x.open-1)*100])}leaders.sort((a,b)=>Math.abs(b[1])-Math.abs(a[1]));const [k,m]=leaders[0],x=S.stocks[k];S.marketWire=x.name+' ('+k+') is '+(m>=0?'up ':'down ')+Math.abs(m).toFixed(1)+'% on the day; '+x.sector.toLowerCase()+' issues remain under observation.';renderStocks();renderHoldings();$('#marketIndex').textContent=marketIndex().toFixed(2);$('#marketWire').textContent=S.marketWire}
function archiveToday(){if(S.newsArchive.some(n=>n.iso===S.gameDate))return;S.newsArchive.push({iso:S.gameDate,date:displayDate(),headline:S.headline,story:S.story,society:S.societyStory});if(S.newsArchive.length>400)S.newsArchive.shift()}
function payMonthlyDividends(oldIso,newIso){if(monthKey(oldIso)===monthKey(newIso))return;let total=0;for(const [k,p] of Object.entries(S.portfolio)){const x=S.stocks[k],amount=p.shares*x.price*x.yieldRate/12;if(amount>.009){total+=amount;S.transactions.push({date:displayDate(),action:'DIVIDEND',ticker:k,shares:p.shares,price:x.price,amount})}}S.personalCash+=total}
function generatePaper(){const d=new Date(S.gameDate+'T12:00:00'),day=d.getDate();if(S.lastRaidOutcome==='caught'){S.headline='PROMINENT INDUSTRIALIST QUESTIONED IN CLUB RAID';S.story='Police activity at a private Washington club has drawn attention to several patrons, including the head of Federal Electric.';S.societyStory='The Star Club raid is the subject of unusually energetic conversation in Washington social circles.';S.lastRaidOutcome=null}else if(S.lastRaidOutcome==='missed'){S.headline='POLICE RAID PRIVATE WASHINGTON CLUB';S.story='Police descended on a private club last evening and detained several patrons for questioning.';S.societyStory='The raid has unsettled bookmakers and private gaming circles across the District.';S.lastRaidOutcome=null}else if(S.companyCash<10000){S.headline='CREDITORS WATCH INDUSTRIAL BALANCE SHEETS';S.story='Tight liquidity has become a concern in several manufacturing offices.';S.societyStory='Bankers report growing attention to industrial credit.'}else{S.headline='FACTORIES WEIGH ORDERS, COSTS AND RECOVERY';S.story='Industrial managers report uneven demand as companies compete for orders and preserve working capital.';S.societyStory=day%3===0?'Private clubs remain busy as businessmen and officials exchange gossip after hours.':'Washington begins another day of meetings, dinners and quiet conversations.'}}
function closeDay(manual=false){archiveToday();if(monthKey(S.gameDate)===S.starNextRaidMonth&&!S.starRaidOccurred){S.starRaidOccurred=true;if(S.contacts.madamStar.met&&Math.random()<.15)S.lastRaidOutcome='missed';S.starNextRaidMonth=rollStarRaidMonth(S.gameDate)}if(isRaidToday()&&S.lastRaidOutcome!=='caught'&&Math.random()<.2)S.lastRaidOutcome='missed';const old=S.gameDate,payroll=S.workers*18;S.companyCash-=payroll;S.lastExpenses+=payroll;S.ledger.push({date:displayDate(),rev:S.lastRevenue,exp:S.lastExpenses});S.lastRevenue=0;S.lastExpenses=0;S.machinery=clamp(S.machinery-.7,20,100);S.gameDate=nextBusinessDay(S.gameDate);payMonthlyDividends(old,S.gameDate);S.dayRemaining=DAY_SECONDS;for(const x of Object.values(S.stocks))x.open=x.price;if(S.raidMonth!==monthKey(S.gameDate)){S.raidMonth=monthKey(S.gameDate);S.raidDays=rollRaidDays(S.gameDate)}generatePaper();save();render();note(manual?'Business day closed early.':'The business day closed automatically.')}
function isRaidToday(){return S.raidDays.includes(new Date(S.gameDate+'T12:00:00').getDate())}
$('#produce').onclick=()=>{const q=$('#quality').value,u=Math.floor(+$('input#units').value),p=+$('input#price').value,cfg={standard:{c:1,g:1,t:.5,cost:.105,rep:.05,demand:1},long:{c:1.12,g:1.08,t:.72,cost:.132,rep:.35,demand:.83},economy:{c:.82,g:.88,t:.35,cost:.079,rep:-.28,demand:1.2}}[q];if(u<100||u>capacity())return note('Production order exceeds limits.');if(S.materials.copper<u*cfg.c||S.materials.glass<u*cfg.g||S.materials.tungsten<u*cfg.t)return note('Insufficient raw materials.');const cost=u*cfg.cost;if(S.companyCash<cost)return note('Insufficient company cash.');S.materials.copper-=u*cfg.c;S.materials.glass-=u*cfg.g;S.materials.tungsten-=u*cfg.t;S.companyCash-=cost;S.lastExpenses+=cost;S.inventory+=u;const sold=Math.min(S.inventory,Math.floor(u*cfg.demand*(.72+Math.random()*.38))),rev=sold*p;S.inventory-=sold;S.companyCash+=rev;S.lastRevenue+=rev;S.reputation=clamp(S.reputation+cfg.rep,0,100);S.machinery=clamp(S.machinery-u/capacity()*3,20,100);note('Order completed: '+sold.toLocaleString()+' units sold for '+money(rev)+'.');save();render()}
$('#maintain').onclick=()=>{if(S.companyCash<750)return note('Insufficient company cash.');S.companyCash-=750;S.lastExpenses+=750;S.machinery=clamp(S.machinery+12,0,100);save();render()}
$('#endDay').onclick=()=>{if(confirm('Close the current business day early?'))closeDay(true)}
$('#save').onclick=()=>save(false);
$('#load').onclick=()=>{const raw=localStorage.getItem(SAVE_KEY)||localStorage.getItem('continentalElectricSave');if(raw){S=migrate(JSON.parse(raw));save();note('Company books restored.');render()}else note('No saved company books found.')}
$('#reset').onclick=()=>{if(confirm('Start a new company?')){S=initial();save();render()}}
$('#archiveEdition').onclick=()=>{archiveToday();save();renderArchive();note('Edition placed in the archive.')}
$('#addNote').onclick=()=>{const text=$('#noteText').value.trim(),source=$('#noteSource').value.trim();if(!text)return;S.notes.push({date:displayDate(),text,source});$('#noteText').value='';$('#noteSource').value='';save();renderNotes()}
$('#visitStar').onclick=()=>{S.contacts.madamStar.met=true;S.contacts.madamStar.trust++;$('#starNote').textContent='You spend part of the day at the Star Club. Madam Star now knows your name.';save();renderWashington()}
$('#meetBookie').onclick=()=>{if(!S.contacts.madamStar.met)return;S.bookieKnown=true;S.contacts.bookie.met=true;S.contacts.bookie.trust++;$('#starNote').textContent='Madam Star introduces you to Eddie Doyle, a bookmaker who handles private wagers.';save();renderWashington()}
function playPokerCircle(circle,stake){if(S.personalCash<stake){$('#pokerNote').textContent='You need '+cash(stake)+' personal cash for this table.';return}if(circle==='elite'&&!S.elitePokerUnlocked){$('#pokerNote').textContent='The private society game requires an introduction.';return}FE_POKER.start(circle)}
window.FE_POKER_EXIT=(circle,delta,hands)=>{S.personalCash+=delta;S.dayRemaining=Math.max(0,S.dayRemaining-Math.min(600,Math.max(60,hands*45)));if(circle==='middle'&&S.contacts.madamStar.trust>=2&&Math.random()<.25)S.elitePokerUnlocked=true;if(isRaidToday()&&Math.random()<pokerRisk(circle)){S.lastRaidOutcome='caught';S.reputation=clamp(S.reputation-(circle==='elite'?7:3),0,100);$('#pokerNote').textContent='The game was caught in a rare police sweep. Your name may reach the morning paper.'}else $('#pokerNote').textContent='You leave the table '+(delta>=0?'ahead ':'down ')+cash(Math.abs(delta))+'. '+hands+' hand'+(hands===1?'':'s')+' played.';save();render()}
$('#pokerWorking').onclick=()=>playPokerCircle('working',25);$('#pokerMiddle').onclick=()=>playPokerCircle('middle',100);$('#pokerElite').onclick=()=>playPokerCircle('elite',500);
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
const sectors=[...new Set(stockSeed.map(x=>x[2]))].sort();$('#sectorFilter').innerHTML='<option value="All">All sectors</option>'+sectors.map(s=>'<option>'+s+'</option>').join('');$('#stockSearch').oninput=renderStocks;$('#sectorFilter').onchange=renderStocks;
loadInitial();render();
marketTimer=setInterval(()=>{if(!document.hidden&&S.dayRemaining>0){moveMarket()}},MARKET_TICK_MS);
clockTimer=setInterval(()=>{if(document.hidden)return;S.dayRemaining=Math.max(0,S.dayRemaining-1);$('#dayClock').textContent=clockText();if(S.dayRemaining<=0)closeDay(false)},1000);
autosaveTimer=setInterval(()=>save(true),5000);
document.addEventListener('visibilitychange',()=>{if(document.hidden)save(true)});
window.addEventListener('pagehide',()=>save(true));