const $=s=>document.querySelector(s), money=n=>'$'+Math.round(n).toLocaleString('en-US'), clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
const initial=()=>({year:1938,month:1,period:0,companyCash:50000,personalCash:12000,debt:0,reputation:55,workers:80,machinery:92,inventory:0,materials:{copper:6000,glass:6000,tungsten:3500},lastRevenue:0,lastExpenses:0,ledger:[],portfolio:{AMW:0,NRT:0,ATL:0,HBC:0},stocks:{AMW:{name:'American Motor Works',sector:'Automotive',price:31.4},NRT:{name:'National Radio & Telegraph',sector:'Communications',price:18.75},ATL:{name:'Atlantic Chemical',sector:'Chemicals',price:24.1},HBC:{name:'Hudson Banking Corp.',sector:'Banking',price:42.6}},headline:'Industry Watches Recovery With Caution',story:'Manufacturers enter 1938 balancing weak demand against hopes for renewed industrial activity.'});
let S=initial(); const periods=['Early','Mid','Late','Month End'];
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active')});
function date(){return periods[S.period]+' '+new Date(S.year,S.month-1,1).toLocaleString('en-US',{month:'long'})+' '+S.year}
function capacity(){return Math.floor(S.workers*20*(S.machinery/100))}
function portfolioValue(){return Object.entries(S.portfolio).reduce((a,[k,q])=>a+q*S.stocks[k].price,0)}
function render(){ $('#companyCash').textContent=money(S.companyCash);$('#personalCash').textContent=money(S.personalCash);$('#companyValue').textContent=money(S.companyCash+S.inventory*.14+Object.values(S.materials).reduce((a,b)=>a+b*.015,0));$('#reputation').textContent=Math.round(S.reputation)+'/100';$('#workers').textContent=S.workers;$('#machinery').textContent=S.machinery.toFixed(1)+'%';$('#capacity').textContent=capacity().toLocaleString();$('#inventory').textContent=S.inventory.toLocaleString();$('#dateFoot').textContent=date();$('#paperDate').textContent='THE METROPOLITAN LEDGER · '+date().toUpperCase();$('#headline').textContent=S.headline;$('#story').textContent=S.story;$('#marketStory').textContent='Industrial shares are '+(Object.values(S.stocks).reduce((a,x)=>a+x.price,0)>115?'firm':'mixed')+'. Continental Electric management is watching credit, materials and consumer demand.';$('#portfolio').textContent=money(portfolioValue());
$('#ledger').innerHTML=S.ledger.slice(-8).reverse().map(x=>'<tr><td>'+x.date+'</td><td>'+money(x.rev)+'</td><td>'+money(x.exp)+'</td><td>'+money(x.rev-x.exp)+'</td></tr>').join('')||'<tr><td colspan="4">No closed periods yet.</td></tr>';
const lots={copper:[1000,180],glass:[1000,95],tungsten:[500,160]};$('#materials').innerHTML=Object.entries(lots).map(([k,[qty,cost]])=>'<tr><td>'+k[0].toUpperCase()+k.slice(1)+'</td><td>'+Math.floor(S.materials[k]).toLocaleString()+'</td><td>'+money(cost)+'</td><td><button onclick="buyMaterial(\''+k+'\','+qty+','+cost+')">Buy '+qty+'</button></td></tr>').join('');
$('#stocks').innerHTML=Object.entries(S.stocks).map(([k,x])=>'<tr><td>'+k+'</td><td>'+x.name+'</td><td>'+x.sector+'</td><td>$'+x.price.toFixed(2)+'</td><td>'+S.portfolio[k]+'</td><td><button onclick="trade(\''+k+'\',10)">Buy 10</button> <button onclick="trade(\''+k+'\',-10)">Sell 10</button></td></tr>').join('')}
window.buyMaterial=(k,q,c)=>{if(S.companyCash<c)return note('Insufficient company cash.');S.companyCash-=c;S.materials[k]+=q;S.lastExpenses+=c;note('Purchase order entered.');render()}
window.trade=(k,q)=>{let cost=S.stocks[k].price*Math.abs(q);if(q>0){if(S.personalCash<cost)return note('Insufficient personal cash.');S.personalCash-=cost;S.portfolio[k]+=q}else{if(S.portfolio[k]<Math.abs(q))return note('Not enough shares.');S.portfolio[k]+=q;S.personalCash+=cost}render()}
function note(t){$('#notice').textContent=t;$('#productionNote').textContent=t}
$('#produce').onclick=()=>{const q=$('#quality').value,u=Math.floor(+$('input#units').value),p=+$('input#price').value, cfg={standard:{c:1,g:1,t:.5,cost:.105,rep:.05,demand:1},long:{c:1.12,g:1.08,t:.72,cost:.132,rep:.35,demand:.83},economy:{c:.82,g:.88,t:.35,cost:.079,rep:-.28,demand:1.2}}[q];if(u<100||u>capacity())return note('Production order exceeds limits.');if(S.materials.copper<u*cfg.c||S.materials.glass<u*cfg.g||S.materials.tungsten<u*cfg.t)return note('Insufficient raw materials.');let cost=u*cfg.cost;if(S.companyCash<cost)return note('Insufficient company cash.');S.materials.copper-=u*cfg.c;S.materials.glass-=u*cfg.g;S.materials.tungsten-=u*cfg.t;S.companyCash-=cost;S.lastExpenses+=cost;S.inventory+=u;let sold=Math.min(S.inventory,Math.floor(u*cfg.demand*(.72+Math.random()*.38)));let rev=sold*p;S.inventory-=sold;S.companyCash+=rev;S.lastRevenue+=rev;S.reputation=clamp(S.reputation+cfg.rep,0,100);S.machinery=clamp(S.machinery-u/capacity()*3,20,100);note('Order completed: '+sold.toLocaleString()+' units sold for '+money(rev)+'.');render()}
$('#maintain').onclick=()=>{if(S.companyCash<750)return note('Insufficient company cash.');S.companyCash-=750;S.lastExpenses+=750;S.machinery=clamp(S.machinery+12,0,100);render()}
$('#advance').onclick=()=>{let payroll=S.workers*18;S.companyCash-=payroll;S.lastExpenses+=payroll;S.ledger.push({date:date(),rev:S.lastRevenue,exp:S.lastExpenses});S.lastRevenue=0;S.lastExpenses=0;Object.values(S.stocks).forEach(x=>x.price=Math.max(2,x.price*(.94+Math.random()*.12)));S.machinery=clamp(S.machinery-.7,20,100);S.period++;if(S.period>3){S.period=0;S.month++;if(S.month>12){S.month=1;S.year++}}if(S.year===1939&&S.month>=9){S.headline='WAR IN EUROPE RESHAPES INDUSTRIAL OUTLOOK';S.story='European conflict dominates the wires. American manufacturers watch export demand, materials and government procurement closely.'}else if(S.companyCash<10000){S.headline='CREDITORS WATCH INDUSTRIAL BALANCE SHEETS';S.story='Tight liquidity has become the chief concern in several manufacturing offices.'}else{S.headline='FACTORIES WEIGH ORDERS, COSTS AND RECOVERY';S.story='Industrial managers report uneven demand as companies compete for orders and preserve working capital.'}render()}
$('#save').onclick=()=>{localStorage.setItem('continentalElectricSave',JSON.stringify(S));note('Company books saved.')} ;$('#load').onclick=()=>{let x=localStorage.getItem('continentalElectricSave');if(x){S=JSON.parse(x);note('Company books restored.');render()}};$('#reset').onclick=()=>{if(confirm('Start a new company?')){S=initial();render()}};render();