/* Federal Electric Poker Engine - browser-native Texas Hold'em */
(()=>{'use strict';
const rooms={
 working:{name:'The Boiler Room',className:'poker-poor',stake:25,blind:1,npcs:[['Mickey Dunn','loose'],['Joe Rourke','bluff'],['Frank Bell','steady']]},
 middle:{name:'The Commerce Club',className:'poker-middle',stake:100,blind:2,npcs:[['Walter Briggs','steady'],['Charles Webb','tight'],['Eddie Doyle','bluff']]},
 elite:{name:'The Embassy Room',className:'poker-elite',stake:500,blind:10,npcs:[['Harrison Vale','tight'],['Sen. Robert Whitmore','steady'],['August Belmont III','aggressive']]}
};
let G=null,sessionStarted=Date.now(),businessStart=3600,clockTimer=null;
const ranks='23456789TJQKA',suits='♣♦♥♠';
function deck(){let d=[];for(let r of ranks)for(let s of suits)d.push({r,s,v:ranks.indexOf(r)+2});for(let i=d.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[d[i],d[j]]=[d[j],d[i]]}return d}
function combos(a,k){let out=[];function go(start,x){if(x.length===k){out.push(x.slice());return}for(let i=start;i<a.length;i++){x.push(a[i]);go(i+1,x);x.pop()}}go(0,[]);return out}
function five(cs){let vals=cs.map(c=>c.v).sort((a,b)=>b-a),cnt={};vals.forEach(v=>cnt[v]=(cnt[v]||0)+1);let uniq=[...new Set(vals)];if(uniq[0]===14)uniq.push(1);let hi=0;for(let i=0;i<=uniq.length-5;i++)if(uniq[i]-uniq[i+4]===4){hi=uniq[i];break}let flush=cs.every(c=>c.s===cs[0].s),groups=Object.entries(cnt).map(([v,n])=>[+v,n]).sort((a,b)=>b[1]-a[1]||b[0]-a[0]);let cat,tie,name;if(flush&&hi){cat=8;tie=[hi];name='Straight Flush'}else if(groups[0][1]===4){cat=7;tie=[groups[0][0],groups[1][0]];name='Four of a Kind'}else if(groups[0][1]===3&&groups[1][1]===2){cat=6;tie=[groups[0][0],groups[1][0]];name='Full House'}else if(flush){cat=5;tie=vals;name='Flush'}else if(hi){cat=4;tie=[hi];name='Straight'}else if(groups[0][1]===3){cat=3;tie=[groups[0][0],...groups.filter(x=>x[1]===1).map(x=>x[0]).sort((a,b)=>b-a)];name='Three of a Kind'}else if(groups[0][1]===2&&groups[1][1]===2){let ps=groups.filter(x=>x[1]===2).map(x=>x[0]).sort((a,b)=>b-a);cat=2;tie=[...ps,groups.find(x=>x[1]===1)[0]];name='Two Pair'}else if(groups[0][1]===2){cat=1;tie=[groups[0][0],...groups.filter(x=>x[1]===1).map(x=>x[0]).sort((a,b)=>b-a)];name='Pair'}else{cat=0;tie=vals;name='High Card'}return{score:[cat,...tie],name}}
function eval7(cs){return combos(cs,5).map(five).sort((a,b)=>cmp(b.score,a.score))[0]}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){let d=(a[i]||0)-(b[i]||0);if(d)return d}return 0}
function card(c,hide=false){return '<span class="p-card '+((c.s==='♥'||c.s==='♦')?'red':'')+(hide?' back':'')+'">'+(hide?'FE':c.r+'<i>'+c.s+'</i>')+'</span>'}
function clockText(n){n=Math.max(0,Math.ceil(n));return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function updateClock(){const elapsed=Math.floor((Date.now()-sessionStarted)/1000);let left=Math.max(0,businessStart-elapsed);try{if(window.opener&&!window.opener.closed&&typeof window.opener.FE_POKER_CLOCK==='function')left=Math.max(0,window.opener.FE_POKER_CLOCK()-elapsed)}catch(e){}const el=document.querySelector('#pokerBusinessClock');if(el)el.textContent=clockText(left)}
function start(roomKey){sessionStarted=Date.now();const raw=new URLSearchParams(location.search).get('remaining');businessStart=raw===null?0:Math.max(0,Number(raw)||0);clearInterval(clockTimer);clockTimer=setInterval(updateClock,250);updateClock();let R=rooms[roomKey];if(!R)return;G={roomKey,R,deck:deck(),board:[],pot:0,street:0,currentBet:0,handNo:0,log:[],players:[{name:'You',style:'human',chips:R.stake,hole:[],fold:false,bet:0},...R.npcs.map(n=>({name:n[0],style:n[1],chips:R.stake,hole:[],fold:false,bet:0}))]};document.querySelector('#pokerModal').className='poker-modal open '+R.className;document.querySelector('#pokerRoomName').textContent=R.name;newHand()}
function newHand(){if(!G)return;G.deck=deck();G.board=[];G.pot=0;G.street=0;G.currentBet=0;G.handNo++;G.log=[];G.players.forEach(p=>{p.fold=p.chips<=0;p.bet=0;p.hole=[G.deck.pop(),G.deck.pop()]});let b=G.R.blind;post(1,b);post(2,b*2);G.currentBet=b*2;log('Blinds posted. Cards are dealt.');bots();render()}
function post(i,n){let p=G.players[i],x=Math.min(n,p.chips);p.chips-=x;p.bet+=x;G.pot+=x}
function log(s){G.log.unshift(s);G.log=G.log.slice(0,7)}
function strength(p){if(G.street===0){let a=p.hole[0].v,b=p.hole[1].v,pair=a===b,suited=p.hole[0].s===p.hole[1].s;return pair?.55+a/35:(a+b)/35+(suited?.08:0)}return eval7([...p.hole,...G.board]).score[0]/8+Math.max(...p.hole.map(c=>c.v))/80}
function botAct(p){if(p.fold||p.chips<=0)return;let need=G.currentBet-p.bet,s=strength(p),noise=Math.random(),agg={tight:-.1,steady:0,loose:.08,bluff:.02,aggressive:.14}[p.style]||0;if(need>0&&s+agg+noise*.22<.38){p.fold=true;log(p.name+' folds.');return}if((s+agg>.72&&Math.random()<.45)||p.style==='bluff'&&Math.random()<.14){let raise=Math.min(p.chips,Math.max(G.R.blind*2,Math.round(G.pot*.3)));post(G.players.indexOf(p),need+raise);G.currentBet=p.bet;log(p.name+' raises to $'+p.bet+'.')}else{post(G.players.indexOf(p),need);log(p.name+(need?' calls.':' checks.'))}}
function bots(){for(let i=1;i<G.players.length;i++)botAct(G.players[i]);let max=Math.max(...G.players.map(p=>p.bet));G.currentBet=max}
function player(action){let p=G.players[0],need=G.currentBet-p.bet;if(action==='fold'){p.fold=true;log('You fold.');return showdown(true)}if(action==='call'){post(0,need);log(need?'You call.':'You check.')}if(action==='raise'){let amt=Math.max(G.R.blind*2,Math.floor(G.pot*.35)),total=need+amt;if(p.chips<=0)return;post(0,total);G.currentBet=p.bet;log('You raise to $'+p.bet+'.')}bots();if(G.players.filter(x=>!x.fold).length===1)return showdown(false);advance()}
function advance(){G.players.forEach(p=>p.bet=0);G.currentBet=0;if(G.street===0){G.deck.pop();G.board.push(G.deck.pop(),G.deck.pop(),G.deck.pop());G.street=1;log('The flop is dealt.')}else if(G.street===1){G.deck.pop();G.board.push(G.deck.pop());G.street=2;log('The turn is dealt.')}else if(G.street===2){G.deck.pop();G.board.push(G.deck.pop());G.street=3;log('The river is dealt.')}else return showdown(false);bots();render()}
function showdown(folded){let live=G.players.filter(p=>!p.fold);if(live.length===1){live[0].chips+=G.pot;log(live[0].name+' takes the pot.')}else{let ranked=live.map(p=>({p,e:eval7([...p.hole,...G.board])})).sort((a,b)=>cmp(b.e.score,a.e.score)),best=ranked[0].e.score,w=ranked.filter(x=>cmp(x.e.score,best)===0),share=Math.floor(G.pot/w.length);w.forEach(x=>x.p.chips+=share);log(w.map(x=>x.p.name).join(' & ')+' win'+(w.length>1?' split':'')+' with '+ranked[0].e.name+'.')}G.pot=0;render(true)}
function render(done=false){if(!G)return;document.querySelector('#pokerPot').textContent='$'+G.pot;document.querySelector('#pokerBoard').innerHTML=G.board.map(c=>card(c)).join('')||'<span class="board-empty">PRE-FLOP</span>';let seats=document.querySelector('#pokerSeats');seats.innerHTML=G.players.map((p,i)=>'<div class="p-seat seat-'+i+(p.fold?' folded':'')+'"><b>'+p.name+'</b><div class="cards">'+p.hole.map(c=>card(c,i!==0&&!done)).join('')+'</div><small>$'+p.chips+' · '+(i===0?'Federal Electric':p.style)+'</small></div>').join('');document.querySelector('#pokerLog').innerHTML=G.log.map(x=>'<div>'+x+'</div>').join('');let p=G.players[0],need=Math.max(0,G.currentBet-p.bet);document.querySelector('#pokerCall').textContent=need?'Call $'+need:'Check';document.querySelector('#pokerActions').style.display=done?'none':'flex';document.querySelector('#pokerNext').style.display=done?'inline-block':'none'}
function leave(){if(!G)return;let delta=G.players[0].chips-G.R.stake;clearInterval(clockTimer);let elapsed=Math.max(1,Math.floor((Date.now()-sessionStarted)/1000));if(window.FE_POKER_EXIT)window.FE_POKER_EXIT(G.roomKey,delta,G.handNo,elapsed);document.querySelector('#pokerModal').className='poker-modal';G=null}
window.FE_POKER={start,action:player,newHand,leave};})();